import geoPage from './geoPage'
import sitePage from './sitePage'
import homePage from './homePage'
import blogPost from './blogPost'
import chantier from './chantier'
import mediaItem from './mediaItem'
import pacPage from './pacPage'
import particuliersPage from './particuliersPage'
import proPage from './proPage'
export const schemaTypes = [homePage, geoPage, pacPage, particuliersPage, proPage, sitePage, blogPost, chantier, mediaItem]
