import { C, F } from '../theme'

export const geologyStyles = {
  statusBox: (kind: 'loading' | 'error' | 'ok'): React.CSSProperties => ({
    background: kind === 'error' ? '#FFF5F2' : C.bgSoft,
    border: '1px solid ' + (kind === 'error' ? C.orange : C.border),
    borderLeft: '3px solid ' + (kind === 'error' ? C.orange : C.accentDark),
    padding: '12px 14px', marginBottom: '16px',
    fontSize: F.base, color: C.text2, lineHeight: 1.55,
  }),
  grid: (): React.CSSProperties => ({ display: 'grid', gridTemplateColumns: '56px minmax(0, 1fr) 260px 180px', border: '1px solid ' + C.border, background: C.bg, marginTop: '16px', marginBottom: '12px', overflow: 'hidden' }),
  headerCell: (): React.CSSProperties => ({ minHeight: '40px', display: 'flex', alignItems: 'center', padding: '0 14px', borderRight: '1px solid ' + C.border, borderBottom: '1px solid ' + C.border, background: C.bgMuted, fontSize: F.sm, fontWeight: 700, color: C.text2 }),
  depthAxis: (): React.CSSProperties => ({ position: 'relative', height: '400px', borderRight: '1px solid ' + C.border, background: C.bgMuted }),
  depthTick: (depthM: number, maxDepthM: number): React.CSSProperties => ({ position: 'absolute', top: (depthM / maxDepthM * 100) + '%', right: '8px', transform: 'translateY(-50%)', fontSize: '10px', color: C.text4, fontWeight: 600 }),
  canvas: (): React.CSSProperties => ({ position: 'relative', height: '400px', borderRight: '1px solid ' + C.border, background: C.bgMuted, overflow: 'hidden' }),
  layerBlock: (topM: number, bottomM: number, maxDepthM: number, color: string): React.CSSProperties => ({ position: 'absolute', left: 0, right: 0, top: (topM / maxDepthM * 100) + '%', height: ((bottomM - topM) / maxDepthM * 100) + '%', background: color, borderBottom: '1px solid rgba(0,0,0,0.12)', display: 'flex', alignItems: 'center', padding: '0 12px', boxSizing: 'border-box' }),
  layerLabel: (dark?: boolean): React.CSSProperties => ({ fontSize: '10px', color: dark ? C.text2 : '#fff', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em', textShadow: dark ? 'none' : '0 1px 1px rgba(0,0,0,0.3)' }),
  hydroOverlay: (topM: number, bottomM: number, maxDepthM: number, strong: boolean): React.CSSProperties => ({ position: 'absolute', left: 0, right: 0, pointerEvents: 'none', top: (topM / maxDepthM * 100) + '%', height: ((bottomM - topM) / maxDepthM * 100) + '%', opacity: strong ? 0.6 : 0.4, zIndex: 5, backgroundImage: strong ? 'repeating-linear-gradient(135deg,rgba(21,101,192,0.95) 0px,rgba(21,101,192,0.95) 3px,transparent 3px,transparent 11px)' : 'repeating-linear-gradient(135deg,rgba(21,101,192,0.8) 0px,rgba(21,101,192,0.8) 2px,transparent 2px,transparent 13px)' }),
  waterLine: (depthM: number, maxDepthM: number): React.CSSProperties => ({ position: 'absolute', left: 0, right: 0, top: (depthM / maxDepthM * 100) + '%', borderTop: '2px dashed #1565C0', zIndex: 8, pointerEvents: 'none' }),
  lambdaSvg: (): React.CSSProperties => ({ position: 'absolute', inset: 0, zIndex: 9, pointerEvents: 'none' }),
  targetLine: (): React.CSSProperties => ({ position: 'absolute', left: 0, right: 0, bottom: 0, height: '4px', background: C.accent, zIndex: 10 }),
  lambdaCol: (): React.CSSProperties => ({ position: 'relative', height: '400px', borderRight: '1px solid ' + C.border, background: C.bg }),
  lambdaRow: (topM: number, bottomM: number, maxDepthM: number): React.CSSProperties => ({ position: 'absolute', left: 0, right: 0, top: (topM / maxDepthM * 100) + '%', height: ((bottomM - topM) / maxDepthM * 100) + '%', display: 'grid', gridTemplateColumns: '48px 1fr', alignItems: 'center', gap: '8px', padding: '0 12px', boxSizing: 'border-box', borderBottom: '1px solid ' + C.border }),
  lambdaVal: (): React.CSSProperties => ({ fontSize: F.sm, fontWeight: 700, color: C.text2, textAlign: 'right' }),
  lambdaMeta: (): React.CSSProperties => ({ fontSize: F.xs, color: C.text2, lineHeight: 1.3, fontWeight: 600 }),
  lambdaDepth: (): React.CSSProperties => ({ display: 'block', fontSize: '10px', color: C.text4, fontWeight: 500, marginTop: '2px' }),
  stratCol: (): React.CSSProperties => ({ position: 'relative', height: '400px', background: C.bg }),
  stratRow: (topM: number, bottomM: number, maxDepthM: number): React.CSSProperties => ({ position: 'absolute', left: 0, right: 0, top: (topM / maxDepthM * 100) + '%', height: ((bottomM - topM) / maxDepthM * 100) + '%', display: 'flex', alignItems: 'center', padding: '0 12px', boxSizing: 'border-box', fontSize: F.xs, color: C.text2, lineHeight: 1.3, borderBottom: '1px solid ' + C.border }),
  summaryGrid: (): React.CSSProperties => ({ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px', marginBottom: '16px' }),
  summaryCard: (): React.CSSProperties => ({ background: C.bgSoft, border: '1px solid ' + C.border, padding: '14px' }),
  summaryLabel: (): React.CSSProperties => ({ fontSize: F.xs, color: C.text4, marginBottom: '4px' }),
  summaryValue: (color?: string): React.CSSProperties => ({ fontSize: '20px', fontWeight: 700, color: color === 'green' ? C.green : C.text }),
  summarySub: (): React.CSSProperties => ({ fontSize: '10px', color: C.text4, marginTop: '2px' }),
  legendRow: (): React.CSSProperties => ({ display: 'flex', gap: '16px', flexWrap: 'wrap', fontSize: F.xs, color: C.text3, marginBottom: '12px', alignItems: 'center' }),
  legendItem: (): React.CSSProperties => ({ display: 'flex', alignItems: 'center', gap: '6px' }),
  warning: (): React.CSSProperties => ({ fontSize: F.xs, color: C.text3, lineHeight: 1.6, padding: '10px 14px', background: C.bgSoft, border: '1px solid ' + C.border, borderLeft: '3px solid ' + C.border, marginBottom: '10px' }),
  sectionTable: (): React.CSSProperties => ({ display: 'grid', gridTemplateColumns: '78px minmax(320px, 1fr) 300px 220px', border: '1px solid ' + C.border, background: C.bg, marginTop: '16px', marginBottom: '12px', overflow: 'hidden' }),
  depthHeader: (): React.CSSProperties => ({ minHeight: '42px', borderRight: '1px solid ' + C.border, borderBottom: '1px solid ' + C.border, background: C.bgMuted, position: 'relative' }),
  verticalDepthLabel: (): React.CSSProperties => ({ position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%, -50%) rotate(-90deg)', fontSize: F.xs, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: C.text4, whiteSpace: 'nowrap' }),
  tableHeader: (): React.CSSProperties => ({ minHeight: '42px', display: 'flex', alignItems: 'center', padding: '0 16px', borderRight: '1px solid ' + C.border, borderBottom: '1px solid ' + C.border, background: C.bgMuted, fontSize: F.base, fontWeight: 700, color: C.text2 }),
  sectionCanvas: (): React.CSSProperties => ({ position: 'relative', height: '420px', borderRight: '1px solid ' + C.border, background: C.bgMuted, overflow: 'hidden' }),
  layerName: (dark?: boolean): React.CSSProperties => ({ fontSize: '10px', color: dark ? C.text2 : '#fff', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.08em', lineHeight: 1.2, textShadow: dark ? 'none' : '0 1px 1px rgba(0,0,0,0.28)' }),
  lambdaCurveSvg: (): React.CSSProperties => ({ position: 'absolute', inset: 0, zIndex: 9, pointerEvents: 'none' }),
  lambdaColumn: (): React.CSSProperties => ({ position: 'relative', height: '420px', borderRight: '1px solid ' + C.border, background: C.bg }),
  lambdaBar: (): React.CSSProperties => ({ height: '2px', background: '#E68A8A' }),
  lambdaLayerName: (): React.CSSProperties => ({ fontSize: F.xs, color: C.text2, lineHeight: 1.25, fontWeight: 600 }),
  lambdaLayerDepth: (): React.CSSProperties => ({ display: 'block', fontSize: '10px', color: C.text4, fontWeight: 500, marginTop: '2px' }),
  lambdaValue: (): React.CSSProperties => ({ fontSize: F.sm, fontWeight: 700, color: C.text2, textAlign: 'right' }),
  stratColumn: (): React.CSSProperties => ({ position: 'relative', height: '420px', background: C.bg }),
  stratRow: (topM: number, bottomM: number, maxDepthM: number): React.CSSProperties => ({ position: 'absolute', left: 0, right: 0, top: (topM / maxDepthM * 100) + '%', height: ((bottomM - topM) / maxDepthM * 100) + '%', display: 'flex', alignItems: 'center', padding: '0 12px', boxSizing: 'border-box', fontSize: F.xs, color: C.text2 }),
  legendRow2: (): React.CSSProperties => ({ display: 'flex', gap: '20px', flexWrap: 'wrap', fontSize: F.xs, color: C.text3, margin: '8px 0 14px' }),
  redLineSample: (): React.CSSProperties => ({ display: 'inline-block', width: '20px', height: '2px', background: '#D12B2B', verticalAlign: 'middle' }),
  yellowLineSample: (): React.CSSProperties => ({ display: 'inline-block', width: '20px', height: '3px', background: C.accent, verticalAlign: 'middle' }),
  hydroSample: (strong: boolean): React.CSSProperties => ({ display: 'inline-block', width: '20px', height: '12px', verticalAlign: 'middle', backgroundImage: strong ? 'repeating-linear-gradient(135deg,rgba(21,101,192,0.95) 0px,rgba(21,101,192,0.95) 3px,transparent 3px,transparent 9px)' : 'repeating-linear-gradient(135deg,rgba(21,101,192,0.7) 0px,rgba(21,101,192,0.7) 2px,transparent 2px,transparent 9px)' }),
}
